//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.07 at 03:53:46 PM CEST 
//


package mx.imageviewer.schema.gestionepagina;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import mx.imageviewer.schema.gestioneopera.Libro;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="titolo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="showNavigatore" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
 *                 &lt;attGroup ref="{http://www.imageViewer.mx/schema/gestionePagina}gIdentificativi"/>
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="showStru" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
 *                 &lt;attGroup ref="{http://www.imageViewer.mx/schema/gestionePagina}gIdentificativi"/>
 *                 &lt;attribute name="costola" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="msgError" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="xlimage" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;group ref="{http://www.imageViewer.mx/schema/gestionePagina}gElementSup"/>
 *                   &lt;attGroup ref="{http://www.imageViewer.mx/schema/gestionePagina}gAElementSup"/>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="IIPImage" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;group ref="{http://www.imageViewer.mx/schema/gestionePagina}gElementSup"/>
 *                   &lt;attGroup ref="{http://www.imageViewer.mx/schema/gestionePagina}gAElementSup"/>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.imageViewer.mx/schema/gestioneOpera}libro" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "titolo",
    "idr",
    "showNavigatore",
    "showStru",
    "msgError",
    "xlimage",
    "iipImage",
    "libro"
})
@XmlRootElement(name = "imageViewer")
public class ImageViewer {

    @XmlElement(required = true)
    protected String titolo;
    @XmlElement(required = true)
    protected String idr;
    protected ImageViewer.ShowNavigatore showNavigatore;
    protected ImageViewer.ShowStru showStru;
    protected String msgError;
    protected ImageViewer.Xlimage xlimage;
    @XmlElement(name = "IIPImage")
    protected ImageViewer.IIPImage iipImage;
    @XmlElement(namespace = "http://www.imageViewer.mx/schema/gestioneOpera")
    protected List<Libro> libro;

    /**
     * Gets the value of the titolo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitolo() {
        return titolo;
    }

    /**
     * Sets the value of the titolo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitolo(String value) {
        this.titolo = value;
    }

    /**
     * Gets the value of the idr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdr() {
        return idr;
    }

    /**
     * Sets the value of the idr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdr(String value) {
        this.idr = value;
    }

    /**
     * Gets the value of the showNavigatore property.
     * 
     * @return
     *     possible object is
     *     {@link ImageViewer.ShowNavigatore }
     *     
     */
    public ImageViewer.ShowNavigatore getShowNavigatore() {
        return showNavigatore;
    }

    /**
     * Sets the value of the showNavigatore property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageViewer.ShowNavigatore }
     *     
     */
    public void setShowNavigatore(ImageViewer.ShowNavigatore value) {
        this.showNavigatore = value;
    }

    /**
     * Gets the value of the showStru property.
     * 
     * @return
     *     possible object is
     *     {@link ImageViewer.ShowStru }
     *     
     */
    public ImageViewer.ShowStru getShowStru() {
        return showStru;
    }

    /**
     * Sets the value of the showStru property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageViewer.ShowStru }
     *     
     */
    public void setShowStru(ImageViewer.ShowStru value) {
        this.showStru = value;
    }

    /**
     * Gets the value of the msgError property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgError() {
        return msgError;
    }

    /**
     * Sets the value of the msgError property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgError(String value) {
        this.msgError = value;
    }

    /**
     * Gets the value of the xlimage property.
     * 
     * @return
     *     possible object is
     *     {@link ImageViewer.Xlimage }
     *     
     */
    public ImageViewer.Xlimage getXlimage() {
        return xlimage;
    }

    /**
     * Sets the value of the xlimage property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageViewer.Xlimage }
     *     
     */
    public void setXlimage(ImageViewer.Xlimage value) {
        this.xlimage = value;
    }

    /**
     * Gets the value of the iipImage property.
     * 
     * @return
     *     possible object is
     *     {@link ImageViewer.IIPImage }
     *     
     */
    public ImageViewer.IIPImage getIIPImage() {
        return iipImage;
    }

    /**
     * Sets the value of the iipImage property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageViewer.IIPImage }
     *     
     */
    public void setIIPImage(ImageViewer.IIPImage value) {
        this.iipImage = value;
    }

    /**
     * Gets the value of the libro property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the libro property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLibro().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Libro }
     * 
     * 
     */
    public List<Libro> getLibro() {
        if (libro == null) {
            libro = new ArrayList<Libro>();
        }
        return this.libro;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;group ref="{http://www.imageViewer.mx/schema/gestionePagina}gElementSup"/>
     *       &lt;attGroup ref="{http://www.imageViewer.mx/schema/gestionePagina}gAElementSup"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "pagina"
    })
    public static class IIPImage {

        @XmlElement(required = true)
        protected List<ImageViewer.IIPImage.Pagina> pagina;
        @XmlAttribute(name = "titolo", required = true)
        protected String titolo;
        @XmlAttribute(name = "idrPadre")
        protected String idrPadre;

        /**
         * Gets the value of the pagina property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the pagina property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPagina().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ImageViewer.IIPImage.Pagina }
         * 
         * 
         */
        public List<ImageViewer.IIPImage.Pagina> getPagina() {
            if (pagina == null) {
                pagina = new ArrayList<ImageViewer.IIPImage.Pagina>();
            }
            return this.pagina;
        }

        /**
         * Gets the value of the titolo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitolo() {
            return titolo;
        }

        /**
         * Sets the value of the titolo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitolo(String value) {
            this.titolo = value;
        }

        /**
         * Gets the value of the idrPadre property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIdrPadre() {
            return idrPadre;
        }

        /**
         * Sets the value of the idrPadre property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIdrPadre(String value) {
            this.idrPadre = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="urlPage" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
         *       &lt;attribute name="link" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="key" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="keyPadre" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Pagina {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "urlPage", required = true)
            @XmlSchemaType(name = "anyURI")
            protected String urlPage;
            @XmlAttribute(name = "link", required = true)
            protected String link;
            @XmlAttribute(name = "key", required = true)
            protected String key;
            @XmlAttribute(name = "keyPadre", required = true)
            protected String keyPadre;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the urlPage property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUrlPage() {
                return urlPage;
            }

            /**
             * Sets the value of the urlPage property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUrlPage(String value) {
                this.urlPage = value;
            }

            /**
             * Gets the value of the link property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLink() {
                return link;
            }

            /**
             * Sets the value of the link property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLink(String value) {
                this.link = value;
            }

            /**
             * Gets the value of the key property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getKey() {
                return key;
            }

            /**
             * Sets the value of the key property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setKey(String value) {
                this.key = value;
            }

            /**
             * Gets the value of the keyPadre property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getKeyPadre() {
                return keyPadre;
            }

            /**
             * Sets the value of the keyPadre property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setKeyPadre(String value) {
                this.keyPadre = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
     *       &lt;attGroup ref="{http://www.imageViewer.mx/schema/gestionePagina}gIdentificativi"/>
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class ShowNavigatore {

        @XmlValue
        protected boolean value;
        @XmlAttribute(name = "idr")
        protected String idr;

        /**
         * Gets the value of the value property.
         * 
         */
        public boolean isValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         */
        public void setValue(boolean value) {
            this.value = value;
        }

        /**
         * Gets the value of the idr property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIdr() {
            return idr;
        }

        /**
         * Sets the value of the idr property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIdr(String value) {
            this.idr = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
     *       &lt;attGroup ref="{http://www.imageViewer.mx/schema/gestionePagina}gIdentificativi"/>
     *       &lt;attribute name="costola" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class ShowStru {

        @XmlValue
        protected boolean value;
        @XmlAttribute(name = "costola")
        protected Boolean costola;
        @XmlAttribute(name = "idr")
        protected String idr;

        /**
         * Gets the value of the value property.
         * 
         */
        public boolean isValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         */
        public void setValue(boolean value) {
            this.value = value;
        }

        /**
         * Gets the value of the costola property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isCostola() {
            if (costola == null) {
                return false;
            } else {
                return costola;
            }
        }

        /**
         * Sets the value of the costola property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setCostola(Boolean value) {
            this.costola = value;
        }

        /**
         * Gets the value of the idr property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIdr() {
            return idr;
        }

        /**
         * Sets the value of the idr property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIdr(String value) {
            this.idr = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;group ref="{http://www.imageViewer.mx/schema/gestionePagina}gElementSup"/>
     *       &lt;attGroup ref="{http://www.imageViewer.mx/schema/gestionePagina}gAElementSup"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "pagina"
    })
    public static class Xlimage {

        @XmlElement(required = true)
        protected List<ImageViewer.IIPImage.Pagina> pagina;
        @XmlAttribute(name = "titolo", required = true)
        protected String titolo;
        @XmlAttribute(name = "idrPadre")
        protected String idrPadre;

        /**
         * Gets the value of the pagina property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the pagina property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPagina().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ImageViewer.IIPImage.Pagina }
         * 
         * 
         */
        public List<ImageViewer.IIPImage.Pagina> getPagina() {
            if (pagina == null) {
                pagina = new ArrayList<ImageViewer.IIPImage.Pagina>();
            }
            return this.pagina;
        }

        /**
         * Gets the value of the titolo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitolo() {
            return titolo;
        }

        /**
         * Sets the value of the titolo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitolo(String value) {
            this.titolo = value;
        }

        /**
         * Gets the value of the idrPadre property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIdrPadre() {
            return idrPadre;
        }

        /**
         * Sets the value of the idrPadre property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIdrPadre(String value) {
            this.idrPadre = value;
        }

    }

}
