//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.07 at 03:53:46 PM CEST 
//


package mx.imageviewer.schema.gestionepagina;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mx.imageviewer.schema.gestionepagina package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mx.imageviewer.schema.gestionepagina
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ImageViewer }
     * 
     */
    public ImageViewer createImageViewer() {
        return new ImageViewer();
    }

    /**
     * Create an instance of {@link ImageViewer.IIPImage }
     * 
     */
    public ImageViewer.IIPImage createImageViewerIIPImage() {
        return new ImageViewer.IIPImage();
    }

    /**
     * Create an instance of {@link ImageViewer.ShowNavigatore }
     * 
     */
    public ImageViewer.ShowNavigatore createImageViewerShowNavigatore() {
        return new ImageViewer.ShowNavigatore();
    }

    /**
     * Create an instance of {@link ImageViewer.ShowStru }
     * 
     */
    public ImageViewer.ShowStru createImageViewerShowStru() {
        return new ImageViewer.ShowStru();
    }

    /**
     * Create an instance of {@link ImageViewer.Xlimage }
     * 
     */
    public ImageViewer.Xlimage createImageViewerXlimage() {
        return new ImageViewer.Xlimage();
    }

    /**
     * Create an instance of {@link ImageViewer.IIPImage.Pagina }
     * 
     */
    public ImageViewer.IIPImage.Pagina createImageViewerIIPImagePagina() {
        return new ImageViewer.IIPImage.Pagina();
    }

}
